version: "3.9"

services:
  frontend:
    image: docker.buddaphest.se/marwinfaiter/league_push_ups:frontend
    build:
      context: ./frontend
      target: develop-stage
    ports:
      - 80:8080
    volumes:
      - ./frontend:/app
    command: /bin/sh -c "yarn serve"
  backend:
    image: docker.buddaphest.se/marwinfaiter/league_push_ups:backend
    build:
      context: ./backend
      target: dev
    environment:
      MYSQL_DATABASE: league_push_ups
      MYSQL_HOST: database
      MYSQL_USER: league_push_ups
      MYSQL_PASSWORD: league_push_ups
    ports:
      - 5000:5000
    volumes:
      - ./backend:/src
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: league_push_ups
      MYSQL_USER: league_push_ups
      MYSQL_PASSWORD: league_push_ups
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb:/var/lib/mysql
  redis:
    image: redis:alpine
    environment:
      TZ: "Europe/Stockholm"
    volumes:
      - redis:/data

volumes:
  mariadb:
  redis:
